ersion: "3.8"

services:
  django_app:
    build: ./django_app
    restart: unless-stopped
    ports:
      - "8090:8000"
    depends_on:
      - ollama
    environment:
      - AI_SERVICE_URL=http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1

volumes:
  ollama: