# Generated by Django 4.1 on 2024-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_remove_dream_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
