# Generated by Django 4.1 on 2024-06-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0004_dream_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
