# Generated by Django 4.1 on 2024-06-18 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0006_dreamlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='dreamlike',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='dreamlike',
            constraint=models.UniqueConstraint(fields=('user', 'dream'), name='unique_like'),
        ),
    ]
