# Generated by Django 4.1 on 2024-06-19 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dreams', '0007_remove_dream_is_liked_dreamlike_liked_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dreamlike',
            name='unique_like',
        ),
        migrations.AddField(
            model_name='dream',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dreamlike',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='dreams.dream'),
        ),
        migrations.AlterUniqueTogether(
            name='dreamlike',
            unique_together={('dream', 'user')},
        ),
    ]
