# Generated by Django 4.1 on 2024-06-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0008_remove_dreamlike_unique_like_dream_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='classification',
            field=models.CharField(blank=True, choices=[('0', 'Nightmare'), ('1', 'Mundane Dream'), ('2', 'Lucid Dream'), ('3', 'Existential Dream'), ('4', 'None')], max_length=1, null=True),
        ),
    ]
