# Generated by Django 4.1 on 2024-06-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0009_dream_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='emotion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dream',
            name='persons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dream',
            name='classification',
            field=models.CharField(blank=True, choices=[('0', 'Nightmare'), ('1', 'Mundane Dream'), ('2', 'Lucid Dream'), ('3', 'Existential Dream'), ('4', 'None')], default='4', max_length=1, null=True),
        ),
    ]
