# Generated by Django 4.1 on 2024-06-27 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dreams', '0010_dream_emotion_dream_persons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='dream',
            name='shared',
        ),
        migrations.CreateModel(
            name='DreamShared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared', models.BooleanField(default=False)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared', to='dreams.dream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dream', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DreamFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='dreams.dream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dream', 'user')},
            },
        ),
    ]
