# Generated by Django 4.1 on 2024-06-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0011_remove_dream_is_favorite_remove_dream_shared_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dreamshared',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dreamshared',
            name='dream',
        ),
        migrations.RemoveField(
            model_name='dreamshared',
            name='user',
        ),
        migrations.AddField(
            model_name='dream',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dream',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DreamFavorite',
        ),
        migrations.DeleteModel(
            name='DreamShared',
        ),
    ]
