# Generated by Django 4.1 on 2024-07-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dream',
            old_name='persons',
            new_name='characters',
        ),
        migrations.AddField(
            model_name='dream',
            name='places',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
