# Generated by Django 4.1 on 2024-07-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0015_rename_persons_dream_characters_dream_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='titles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
