# Generated by Django 4.1 on 2024-07-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0016_dream_titles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dream',
            old_name='titles',
            new_name='optional_titles',
        ),
        migrations.AddField(
            model_name='dream',
            name='title',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
