# Generated by Django 4.1 on 2024-07-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0017_rename_titles_dream_optional_titles_dream_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='is_dream',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dream',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
