# Generated by Django 4.1 on 2024-07-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0018_dream_is_dream_alter_dream_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='is_dream',
        ),
    ]
