# Generated by Django 4.1 on 2024-07-12 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0019_remove_dream_is_dream'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dream',
            name='classification',
            field=models.CharField(blank=True, choices=[('0', 'Nightmare'), ('1', 'Mundane Dream'), ('2', 'Lucid Dream'), ('3', 'Existential Dream')], default='', max_length=1, null=True),
        ),
    ]
