# Generated by Django 4.1 on 2024-07-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0020_dream_time_alter_dream_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='time',
            field=models.TimeField(),
        ),
    ]
