# Generated by Django 4.1 on 2024-07-16 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0024_alter_dream_time_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 16, 8, 51, 5, 892201)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
