# Generated by Django 4.1 on 2024-07-22 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0025_alter_dream_time_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='dream_embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dream',
            name='similar_dreams',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dream',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
