# Generated by Django 4.1 on 2024-07-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0026_dream_dream_embedding_dream_similar_dreams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='dream_embedding',
        ),
    ]
