# Generated by Django 4.1 on 2024-07-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0027_remove_dream_dream_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='similar_dreams',
        ),
    ]
