# Generated by Django 4.1 on 2024-07-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0028_remove_dream_similar_dreams'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
