# Generated by Django 4.1 on 2024-07-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0029_dream_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='embedding',
        ),
    ]
