# Generated by Django 4.1 on 2024-08-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0031_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='1.jpg', upload_to='profile_images'),
        ),
    ]
