# Generated by Django 4.1 on 2024-08-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0032_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('1.jpg', 'Picture 1'), ('3.jpg', 'Picture 3'), ('4.jpg', 'Picture 4'), ('5.jpg', 'Picture 5'), ('6.jpg', 'Picture 6'), ('7.jpg', 'Picture 7'), ('8.jpg', 'Picture 8'), ('9.jpg', 'Picture 9'), ('10.jpg', 'Picture 10'), ('11.jpg', 'Picture 11'), ('12.jpg', 'Picture 12'), ('13.jpg', 'Picture 13')], default='1.jpg', max_length=100),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress', models.BooleanField(null=True)),
                ('creativity', models.BooleanField(null=True)),
                ('sleep_duration', models.IntegerField()),
                ('sleep_quality', models.CharField(blank=True, choices=[('0', 'Very poor'), ('1', 'Poor'), ('2', 'Neutral'), ('3', 'Good'), ('4', 'Very Good')], default='', max_length=1, null=True)),
                ('awakening', models.BooleanField(null=True)),
                ('morning_mood', models.CharField(blank=True, choices=[('0', 'Very poor'), ('1', 'Poor'), ('2', 'Neutral'), ('3', 'Good'), ('4', 'Very Good')], default='', max_length=1, null=True)),
                ('dream_relation_oneself', models.BooleanField(null=True)),
                ('dream_impact_mood', models.BooleanField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='dreams.dream')),
            ],
        ),
    ]
