# Generated by Django 4.1 on 2024-09-12 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dreams', '0034_alter_questionnaire_awakening_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('dream_count', models.PositiveIntegerField(default=0)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('classification', models.JSONField(blank=True, default=list)),
                ('characters', models.JSONField(blank=True, default=list)),
                ('places', models.JSONField(blank=True, default=list)),
                ('emotion', models.CharField(blank=True, max_length=20)),
                ('avg_stress', models.FloatField(default=0)),
                ('avg_sleep_duration', models.FloatField(default=0)),
                ('avg_sleep_quality', models.FloatField(default=0)),
                ('count_awakening', models.PositiveIntegerField(default=0)),
                ('count_creativity', models.PositiveIntegerField(default=0)),
                ('count_morning_mood', models.PositiveIntegerField(default=0)),
                ('count_dream_relation_oneself', models.PositiveIntegerField(default=0)),
                ('count_dream_impact_mood', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
