# Generated by Django 4.1 on 2024-09-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0035_monthlyrecap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyrecap',
            old_name='characters',
            new_name='top_characters',
        ),
        migrations.RenameField(
            model_name='monthlyrecap',
            old_name='classification',
            new_name='top_classification',
        ),
        migrations.RenameField(
            model_name='monthlyrecap',
            old_name='emotion',
            new_name='top_emotion',
        ),
        migrations.RenameField(
            model_name='monthlyrecap',
            old_name='keywords',
            new_name='top_keywords',
        ),
        migrations.RenameField(
            model_name='monthlyrecap',
            old_name='places',
            new_name='top_places',
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_sleep_duration',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_sleep_quality',
            field=models.JSONField(default=dict),
        ),
    ]
