# Generated by Django 4.1 on 2024-09-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0036_rename_characters_monthlyrecap_top_characters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrecap',
            name='classification_sleep_duration_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='classification_sleep_quality_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='classification_stress_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
