# Generated by Django 4.1 on 2024-09-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0037_monthlyrecap_classification_sleep_duration_counts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrecap',
            name='classification_sleep_duration_counts',
        ),
        migrations.RemoveField(
            model_name='monthlyrecap',
            name='classification_sleep_quality_counts',
        ),
        migrations.RemoveField(
            model_name='monthlyrecap',
            name='classification_stress_counts',
        ),
    ]
