# Generated by Django 4.1 on 2024-09-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0038_remove_monthlyrecap_classification_sleep_duration_counts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyrecap',
            old_name='count_awakening',
            new_name='avg_awakening',
        ),
        migrations.RenameField(
            model_name='monthlyrecap',
            old_name='count_creativity',
            new_name='avg_creativity',
        ),
        migrations.RenameField(
            model_name='monthlyrecap',
            old_name='count_dream_impact_mood',
            new_name='avg_dream_impact_mood',
        ),
        migrations.RenameField(
            model_name='monthlyrecap',
            old_name='count_dream_relation_oneself',
            new_name='avg_dream_relation_oneself',
        ),
        migrations.RenameField(
            model_name='monthlyrecap',
            old_name='count_morning_mood',
            new_name='avg_morning_mood',
        ),
        migrations.RenameField(
            model_name='monthlyrecap',
            old_name='avg_sleep_duration',
            new_name='most_common_sleep_duration',
        ),
        migrations.RenameField(
            model_name='monthlyrecap',
            old_name='avg_sleep_quality',
            new_name='most_common_sleep_duration_nightmares',
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='avg_nightmare_awakening',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='avg_nightmare_creativity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='avg_nightmare_dream_impact_mood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='avg_nightmare_dream_relation_oneself',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='avg_nightmare_morning_mood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='avg_nightmare_stress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='most_common_sleep_quality',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='most_common_sleep_quality_nightmares',
            field=models.JSONField(default=dict),
        ),
    ]
