# Generated by Django 4.1 on 2024-09-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0039_rename_count_awakening_monthlyrecap_avg_awakening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_awakening',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_creativity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_dream_impact_mood',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_dream_relation_oneself',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_morning_mood',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_nightmare_awakening',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_nightmare_creativity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_nightmare_dream_impact_mood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_nightmare_dream_relation_oneself',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_nightmare_morning_mood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_nightmare_stress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_stress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='most_common_sleep_duration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='most_common_sleep_duration_nightmares',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='most_common_sleep_quality_nightmares',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
