# Generated by Django 4.1 on 2024-09-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0040_alter_monthlyrecap_avg_awakening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_awakening',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_creativity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_dream_impact_mood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_dream_relation_oneself',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecap',
            name='avg_morning_mood',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
