# Generated by Django 4.1 on 2024-09-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0041_alter_monthlyrecap_avg_awakening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrecap',
            name='top_characters_nightmare',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='top_emotion_nightmare',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='top_keywords_nightmare',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monthlyrecap',
            name='top_places_nightmare',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
